# Generated by Django 2.2.2 on 2020-10-17 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.BigIntegerField(null=True)),
                ('name', models.CharField(max_length=256, null=True)),
                ('surname', models.CharField(max_length=256, null=True)),
                ('birthday', models.DateField(null=True)),
                ('age', models.IntegerField(null=True)),
                ('gender_code', models.CharField(max_length=1, null=True)),
                ('directory', models.CharField(max_length=256, null=True)),
                ('aMRG_eop', models.DecimalField(decimal_places=2, max_digits=30, null=True)),
                ('aCSH_eop', models.DecimalField(decimal_places=2, max_digits=30, null=True)),
                ('aCRD_eop', models.DecimalField(decimal_places=2, max_digits=30, null=True)),
                ('pCUR_eop', models.DecimalField(decimal_places=2, max_digits=30, null=True)),
                ('pCRD_eop', models.DecimalField(decimal_places=2, max_digits=30, null=True)),
                ('pSAV_eop', models.DecimalField(decimal_places=2, max_digits=30, null=True)),
                ('pDEP_eop', models.DecimalField(decimal_places=2, max_digits=30, null=True)),
                ('sWork_S', models.DecimalField(decimal_places=2, max_digits=30, null=True)),
                ('tPOS_S', models.DecimalField(decimal_places=2, max_digits=30, null=True)),
                ('isPremium', models.BooleanField(null=True)),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MCC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MCC_CD', models.DecimalField(decimal_places=0, max_digits=4, null=True)),
                ('GroupName', models.CharField(max_length=256, null=True)),
                ('Description', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['updated_at'], 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.RemoveField(
            model_name='task',
            name='date',
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TRANSACTION_DT', models.DateField(null=True)),
                ('MCC_KIND_CD', models.CharField(max_length=256, null=True)),
                ('CARD_AMOUNT_EQV_CBR', models.DecimalField(decimal_places=2, max_digits=30, null=True)),
                ('MCC_CD', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenders.MCC')),
                ('client_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenders.Client')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalTask',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('comment', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Обновлено')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('state', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenders.TaskState', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'historical Задача',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
