# Generated by Django 2.2.2 on 2020-10-17 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0004_auto_20201017_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='gender_code',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
