# Generated by Django 2.2.2 on 2020-10-17 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0005_auto_20201017_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='birthday',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
