# Generated by Django 2.2.2 on 2020-10-17 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0006_auto_20201017_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='computed_field',
        ),
    ]
