# Generated by Django 2.2.2 on 2020-10-17 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0007_remove_client_computed_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='computed_field',
            field=models.BooleanField(editable=False, null=True),
        ),
    ]
