# Generated by Django 2.2.2 on 2020-10-17 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0008_client_computed_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='computed_field',
        ),
        migrations.AlterField(
            model_name='client',
            name='isPremium',
            field=models.BooleanField(editable=False, null=True),
        ),
    ]
