# Generated by Django 2.2.2 on 2020-10-17 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0009_auto_20201017_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='client',
            name='isPremium',
        ),
        migrations.RemoveField(
            model_name='mcc',
            name='MCC_CD',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='TRANSACTION_DT',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
