# Generated by Django 2.2.2 on 2020-10-18 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0010_auto_20201017_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='isPremium',
            field=models.BooleanField(null=True),
        ),
    ]
